### ISSUE TITLE
Transparent background option (RC->Style->Background)

### ISSUE THREAD

**Issue by Guilherme-Routar** [knoxfighter/GW2-ArcDPS-Boon-Table#13]
Hello, are there any plans to add _non hover transparency_? Or any sort of transparency really. Somewhat similar to arcdps' damage meter, where u can set a transparent background color

**Comment by knoxfighter** [comment]
When you set the background color of arcdps the background color of the boon table changes too. 
Which color exactly do you want to change? What is the option you changed and you think is not working like expected?

**Comment by CaptainZlick** [comment]
I don't know if it belongs to the same topic, but I would like to have a setting to make the background transparent, like in ArcDPS (style -> background).

**Comment by knoxfighter** [comment]
> When you set the background color of arcdps the background color of the boon table changes too.
> Which color exactly do you want to change? What is the option you changed and you think is not working like expected?

This also counts for you @CaptainZlick. Please answer my two questions (with screenshots if you want) and i will be able to help.

**Comment by CaptainZlick** [comment]
![1](https://user-images.githubusercontent.com/5216743/115603802-e1d2e180-a2e0-11eb-82e1-8c639cc0d2c7.jpg)
Purple = Option in ArcDPS to activate the transparency
Red = ArcDPS with the transparency option enabled
Green = Boon table with background (the purplish, grayish should be transparent)
Blue = The purple background should be transparent too

**Comment by knoxfighter** [comment]
aah, i didn't knew that button exists, i will add something similar :)

**Comment by knoxfighter** [comment]
Implemented in v2.2.0
