### ISSUE TITLE
Restore sizing policy

### ISSUE THREAD

**Issue by CaptainZlick** [knoxfighter/GW2-ArcDPS-Boon-Table#14]
Hey, I would like to have implemented that the last set configuration for "sizing policy" is restored after a restart of the client.

**Comment by knoxfighter** [comment]
It should save it just fine. Is a file `<Gw2>/addons/arcdps/arcdps_table.ini` generated? When that file exists, just delete it (it will reset all your setitngs but all future settings will be saved again)

**Comment by CaptainZlick** [comment]
Thanks, it worked for me. There was the configuration from the previous version of the boon table, which was not overwritten.
