### ISSUE TITLE
Crash in Wvw

### ISSUE THREAD

**Issue by DoNotBlameItOnMe** [knoxfighter/GW2-ArcDPS-Boon-Table#16]
it's sems boon table make me crash in wold v world

Jul 15 18:02:33 arcdps 20210713.173445-372-x64
Jul 15 18:02:33 client: gw2 0x7FF6D34B0000-0x7FF6D59DC000 (0xE7495DCB)
Jul 15 18:02:33 client: arcdps 0x7FFF93CD0000-0x7FFF93DFD000 (0xDB8007D5)
Jul 15 18:02:33 client: chainloading d3d9
Jul 15 18:02:33 extensions: Boon Table 0x7FFF93B50000-0x7FFF93BFC000 (Apr 12 2021, 0xB63CCCF0)
Jul 15 18:02:33 config: loading from "C:\Guild Wars 2\addons\arcdps\arcdps.ini"
Jul 15 18:02:33 client: ready
Jul 15 18:17:09 error: intercepted crash from hardware exception in "C:\Guild Wars 2\bin64\d3d9_arcdps_table.dll"
Jul 15 18:17:09 client: --- exception ---
			code: 0x00000000C0000005
			addr: 0x00007FFF93BA0325
			offs: 0x0000000000050325
			prms:   0000000000000002
			flgs: 0x0000000000000000
Jul 15 18:17:09 client: --- system ---
			windows: 10.0
			cpu: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
			ram: 11997MB / 16310MB used
			gpu: NVIDIA GeForce GTX 1660 SUPER
Jul 15 18:17:09 client: --- modules ---
			0x7FF6D34B0000 - 0x7FF6D59DC000    C:\Guild Wars 2\Gw2-64.exe
			0x7FFFB2FB0000 - 0x7FFFB31A5000    C:\Windows\SYSTEM32\ntdll.dll
			0x7FFFB1690000 - 0x7FFFB174D000    C:\Windows\System32\KERNEL32.DLL
			0x7FFFB07F0000 - 0x7FFFB0AB9000    C:\Windows\System32\KERNELBASE.dll
			0x7FFFB2D30000 - 0x7FFFB2ED0000    C:\Windows\System32\USER32.dll
			0x7FFFB0D50000 - 0x7FFFB0D72000    C:\Windows\System32\win32u.dll
			0x7FFFB1A10000 - 0x7FFFB1A3A000    C:\Windows\System32\GDI32.dll
			0x7FFFB0D80000 - 0x7FFFB0E8B000    C:\Windows\System32\gdi32full.dll
			0x7FFFB0CB0000 - 0x7FFFB0D4D000    C:\Windows\System32\msvcp_win.dll
			0x7FFFB06F0000 - 0x7FFFB07F0000    C:\Windows\System32\ucrtbase.dll
			0x7FFFB1CA0000 - 0x7FFFB1D4C000    C:\Windows\System32\ADVAPI32.dll
			0x7FFFB15F0000 - 0x7FFFB168E000    C:\Windows\System32\msvcrt.dll
			0x7FFFB2ED0000 - 0x7FFFB2F6B000    C:\Windows\System32\sechost.dll
			0x7FFFB1380000 - 0x7FFFB14AA000    C:\Windows\System32\RPCRT4.dll
			0x7FFFB19A0000 - 0x7FFFB1A0B000    C:\Windows\System32\WS2_32.dll
			0x7FFFB0C50000 - 0x7FFFB0CB0000    C:\Windows\System32\WINTRUST.dll
			0x7FFFB1930000 - 0x7FFFB1938000    C:\Windows\System32\PSAPI.DLL
			0x7FFFAA550000 - 0x7FFFAA55A000    C:\Windows\SYSTEM32\VERSION.dll
			0x7FFFABC50000 - 0x7FFFABC64000    C:\Windows\SYSTEM32\WTSAPI32.dll
			0x7FFFB1AF0000 - 0x7FFFB1C1A000    C:\Windows\System32\ole32.dll
			0x7FFFA1150000 - 0x7FFFA1177000    C:\Windows\SYSTEM32\WINMM.dll
			0x7FFFB1020000 - 0x7FFFB1375000    C:\Windows\System32\combase.dll
			0x7FFFB1800000 - 0x7FFFB18CD000    C:\Windows\System32\OLEAUT32.dll
			0x7FFFB1F40000 - 0x7FFFB267F000    C:\Windows\System32\SHELL32.dll
			0x7FFFADDC0000 - 0x7FFFADDDE000    C:\Windows\SYSTEM32\MSACM32.dll
			0x7FFFB0AC0000 - 0x7FFFB0C1F000    C:\Windows\System32\CRYPT32.dll
			0x7FFF99B80000 - 0x7FFF99D2B000    C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.1081_none_91a70388cc8594fd\gdiplus.dll
			0x7FFF97840000 - 0x7FFF978F0000    C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1083_none_792b8267244587cc\COMCTL32.dll
			0x7FFF99650000 - 0x7FFF99676000    C:\Windows\SYSTEM32\winmmbase.dll
			0x7FFFAD3A0000 - 0x7FFFAD3B9000    C:\Windows\SYSTEM32\USP10.dll
			0x7FFF99B70000 - 0x7FFF99B77000    C:\Windows\SYSTEM32\MSIMG32.dll
			0x7FFF8E980000 - 0x7FFF8E98C000    C:\Windows\SYSTEM32\Secur32.dll
			0x7FFFB00C0000 - 0x7FFFB00CC000    C:\Windows\SYSTEM32\CRYPTBASE.DLL
			0x7FFFB05B0000 - 0x7FFFB05E1000    C:\Windows\SYSTEM32\SSPICLI.DLL
			0x7FFFB1D50000 - 0x7FFFB1D80000    C:\Windows\System32\IMM32.DLL
			0x7FFFB02E0000 - 0x7FFFB02F2000    C:\Windows\SYSTEM32\MSASN1.dll
			0x7FFFB0E90000 - 0x7FFFB0F13000    C:\Windows\System32\bcryptPrimitives.dll
			0x7FFF971C0000 - 0x7FFF973A4000    C:\Windows\SYSTEM32\dbghelp.dll
			0x7FFFAE840000 - 0x7FFFAEFD1000    C:\Windows\SYSTEM32\windows.storage.dll
			0x7FFFB0160000 - 0x7FFFB018C000    C:\Windows\SYSTEM32\Wldp.dll
			0x7FFFB1A40000 - 0x7FFFB1AEE000    C:\Windows\System32\SHCORE.dll
			0x7FFFB26B0000 - 0x7FFFB2705000    C:\Windows\System32\shlwapi.dll
			0x7FFFB0630000 - 0x7FFFB064F000    C:\Windows\SYSTEM32\profapi.dll
			0x7FFFAE560000 - 0x7FFFAE572000    C:\Windows\SYSTEM32\kernel.appcore.dll
			0x7FFFB0C20000 - 0x7FFFB0C47000    C:\Windows\System32\bcrypt.dll
			0x7FFFAE130000 - 0x7FFFAE1CE000    C:\Windows\system32\uxtheme.dll
			0x7FFFAA210000 - 0x7FFFAA241000    C:\Windows\SYSTEM32\cryptnet.dll
			0x7FFFB2680000 - 0x7FFFB269D000    C:\Windows\System32\imagehlp.dll
			0x7FFFB00A0000 - 0x7FFFB00B8000    C:\Windows\SYSTEM32\CRYPTSP.dll
			0x7FFFAF7F0000 - 0x7FFFAF824000    C:\Windows\system32\rsaenh.dll
			0x7FFFA8320000 - 0x7FFFA835B000    C:\Windows\SYSTEM32\dxcore.dll
			0x7FFFB0F20000 - 0x7FFFB0F6E000    C:\Windows\System32\cfgmgr32.dll
			0x7FFFAEFF0000 - 0x7FFFAF013000    C:\Windows\SYSTEM32\gpapi.dll
			0x7FFFB1750000 - 0x7FFFB17F9000    C:\Windows\System32\clbcatq.dll
			0x7FFFAF420000 - 0x7FFFAF453000    C:\Windows\SYSTEM32\ntmarta.dll
			0x7FFFAD380000 - 0x7FFFAD397000    C:\Windows\system32\napinsp.dll
			0x7FFFAD360000 - 0x7FFFAD37B000    C:\Windows\system32\pnrpnsp.dll
			0x7FFFAB830000 - 0x7FFFAB845000    C:\Windows\system32\wshbth.dll
			0x7FFFACC90000 - 0x7FFFACCAD000    C:\Windows\system32\NLAapi.dll
			0x7FFFAFB60000 - 0x7FFFAFB9B000    C:\Windows\SYSTEM32\IPHLPAPI.DLL
			0x7FFFAFEC0000 - 0x7FFFAFF2A000    C:\Windows\System32\mswsock.dll
			0x7FFFAFBA0000 - 0x7FFFAFC6C000    C:\Windows\SYSTEM32\DNSAPI.dll
			0x7FFFB1F30000 - 0x7FFFB1F38000    C:\Windows\System32\NSI.dll
			0x7FFFAD340000 - 0x7FFFAD352000    C:\Windows\System32\winrnr.dll
			0x7FFFA8190000 - 0x7FFFA820F000    C:\Windows\System32\fwpuclnt.dll
			0x7FFFAA0A0000 - 0x7FFFAA0AA000    C:\Windows\System32\rasadhlp.dll
			0x7FFFB2B80000 - 0x7FFFB2C95000    C:\Windows\System32\msctf.dll
			0x7FFFA7B20000 - 0x7FFFA7C19000    C:\Windows\SYSTEM32\textinputframework.dll
			0x7FFFAD930000 - 0x7FFFADC8E000    C:\Windows\System32\CoreUIComponents.dll
			0x7FFFADC90000 - 0x7FFFADD82000    C:\Windows\System32\CoreMessaging.dll
			0x7FFFAC460000 - 0x7FFFAC5B4000    C:\Windows\SYSTEM32\wintypes.dll
			0x7FFFAA350000 - 0x7FFFAA504000    C:\Windows\SYSTEM32\WindowsCodecs.dll
			0x7FFF9ED20000 - 0x7FFF9EDCC000    C:\Windows\SYSTEM32\TextShaping.dll
			0x7FFF93E00000 - 0x7FFF93F14000    C:\Guild Wars 2\bin64\CoherentUI64.dll
			0x7FFF93CD0000 - 0x7FFF93DFD000    C:\Guild Wars 2\bin64\d3d9.dll
			0x7FFFA9500000 - 0x7FFFA960A000    C:\Windows\SYSTEM32\WINHTTP.dll
			0x7FFFAA510000 - 0x7FFFAA51B000    C:\Windows\SYSTEM32\WINNSI.DLL
			0x7FFFAA600000 - 0x7FFFAA617000    C:\Windows\SYSTEM32\dhcpcsvc6.DLL
			0x7FFFAA5E0000 - 0x7FFFAA5FD000    C:\Windows\SYSTEM32\dhcpcsvc.DLL
			0x7FFF97930000 - 0x7FFF979CE000    C:\Windows\SYSTEM32\webio.dll
			0x7FFFB04F0000 - 0x7FFFB04FA000    C:\Windows\SYSTEM32\DPAPI.dll
			0x7FFF93C00000 - 0x7FFF93CCD000    C:\Guild Wars 2\bin64\d3d9_chainload.dll
			0x7FFF73990000 - 0x7FFF73D87000    C:\Guild Wars 2\dxgi.dll
			0x7FFFAD270000 - 0x7FFFAD28B000    C:\Windows\SYSTEM32\VCRUNTIME140.dll
			0x7FFFAD290000 - 0x7FFFAD29C000    C:\Windows\SYSTEM32\VCRUNTIME140_1.dll
			0x7FFF94C50000 - 0x7FFF94CDD000    C:\Windows\SYSTEM32\MSVCP140.dll
			0x7FFF9E270000 - 0x7FFF9E74D000    C:\Windows\SYSTEM32\WININET.dll
			0x7FFFAB5A0000 - 0x7FFFAB5C0000    C:\Windows\SYSTEM32\d3d12.dll
			0x7FFFAC830000 - 0x7FFFACC8D000    C:\Windows\SYSTEM32\d3dcompiler_47.dll
			0x7FFFA0E20000 - 0x7FFFA0FEE000    C:\Windows\system32\d3d9.dll
			0x7FFFAE530000 - 0x7FFFAE55F000    C:\Windows\SYSTEM32\dwmapi.dll
			0x7FFFA75F0000 - 0x7FFFA76F6000    C:\Windows\System32\DriverStore\FileRepository\nvmdi.inf_amd64_b1d015fb0590e821\nvldumdx.dll
			0x7FFF6ECA0000 - 0x7FFF7054F000    C:\Windows\System32\DriverStore\FileRepository\nvmdi.inf_amd64_b1d015fb0590e821\nvd3dumx.dll
			0x7FFFA06F0000 - 0x7FFFA0E08000    C:\Windows\SYSTEM32\nvapi64.dll
			0x7FFFB2710000 - 0x7FFFB2B79000    C:\Windows\System32\SETUPAPI.dll
			0x7FFFAF490000 - 0x7FFFAF4EA000    C:\Windows\SYSTEM32\WINSTA.dll
			0x7FFFA5F60000 - 0x7FFFA6210000    C:\Windows\SYSTEM32\iertutil.dll
			0x7FFF8C250000 - 0x7FFF8C267000    C:\Windows\SYSTEM32\ondemandconnroutehelper.dll
			0x7FFFA5C30000 - 0x7FFFA5E1C000    C:\Windows\SYSTEM32\urlmon.dll
			0x7FFFAF710000 - 0x7FFFAF7A1000    C:\Windows\system32\schannel.DLL
			0x7FFF904E0000 - 0x7FFF904F6000    C:\Windows\SYSTEM32\mskeyprotect.dll
			0x7FFFB0190000 - 0x7FFFB01CB000    C:\Windows\SYSTEM32\NTASN1.dll
			0x7FFFB01D0000 - 0x7FFFB01F7000    C:\Windows\SYSTEM32\ncrypt.dll
			0x7FFF90B20000 - 0x7FFF90B46000    C:\Windows\system32\ncryptsslp.dll
			0x7FFFAF020000 - 0x7FFFAF114000    C:\Windows\system32\dxgi.dll
			0x7FFF73330000 - 0x7FFF734FF000    C:\Windows\SYSTEM32\D3D12Core.dll
			0x7FFF74B80000 - 0x7FFF79580000    C:\Windows\System32\DriverStore\FileRepository\nvmdi.inf_amd64_b1d015fb0590e821\nvwgf2umx.dll
			0x7FFF9E7E0000 - 0x7FFF9E80B000    C:\Windows\SYSTEM32\D3DSCache.dll
			0x7FFFB05F0000 - 0x7FFFB061E000    C:\Windows\SYSTEM32\USERENV.dll
			0x7FFFAA620000 - 0x7FFFAA821000    C:\Windows\SYSTEM32\twinapi.appcore.dll
			0x7FFF93B50000 - 0x7FFF93BFC000    C:\Guild Wars 2\bin64\d3d9_arcdps_table.dll
			0x7FFF945F0000 - 0x7FFF94776000    C:\Windows\System32\Speech\Common\sapi.dll
			0x7FFFADDB0000 - 0x7FFFADDBB000    C:\Windows\SYSTEM32\msdmo.dll
			0x7FFFA9830000 - 0x7FFFA98B5000    C:\Windows\System32\MMDevApi.dll
			0x7FFFB04A0000 - 0x7FFFB04CC000    C:\Windows\System32\DEVOBJ.dll
			0x7FFFAD3C0000 - 0x7FFFAD5A6000    C:\Windows\SYSTEM32\dcomp.dll
			0x7FFF97B40000 - 0x7FFF97B86000    C:\Windows\SYSTEM32\wdmaud.drv
			0x7FFFAA9C0000 - 0x7FFFAA9CA000    C:\Windows\SYSTEM32\AVRT.dll
			0x7FFFAB590000 - 0x7FFFAB599000    C:\Windows\SYSTEM32\ksuser.dll
			0x7FFF97650000 - 0x7FFF977D1000    C:\Windows\SYSTEM32\AUDIOSES.DLL
			0x7FFFAFCD0000 - 0x7FFFAFD1B000    C:\Windows\SYSTEM32\powrprof.dll
			0x7FFFAFB40000 - 0x7FFFAFB52000    C:\Windows\SYSTEM32\UMPDC.dll
			0x7FFFA7DA0000 - 0x7FFFA7DAD000    C:\Windows\SYSTEM32\msacm32.drv
			0x7FFFA7D90000 - 0x7FFFA7D9B000    C:\Windows\SYSTEM32\midimap.dll
			0x7FFFAE250000 - 0x7FFFAE264000    C:\Windows\SYSTEM32\resourcepolicyclient.dll
			0x7FFFAA110000 - 0x7FFFAA1BE000    C:\Windows\SYSTEM32\mscms.dll
			0x7FFFAA0D0000 - 0x7FFFAA0E1000    C:\Windows\SYSTEM32\ColorAdapterClient.dll
			0x7FFF95040000 - 0x7FFF95083000    C:\Windows\SYSTEM32\icm32.dll
			0x7FFF88CB0000 - 0x7FFF88DE9000    C:\Windows\SYSTEM32\dxilconv.dll
Jul 15 18:17:09 client: --- registers ---
			RAX: 0xFFFFFFFFFFFFFFFF   R8:  0x0000022D2327F450
			RBX: 0x0000022D2327F450   R9:  0x0000022C59202B60
			RCX: 0x0000000000000000   R10: 0x00007FFF93BA0210
			RDX: 0x0000022D2327F428   R11: 0x0000022D337CEA40
			RBP: 0x00007FFF93BC3D10   R12: 0x00000000000000C2
			RSP: 0x0000003F67DFF930   R13: 0x0000000000000000
			RSI: 0x00007FFF93BC3B08   R14: 0x0000022D2327F478
			RDI: 0x0000022D2327F428   R15: 0x0000000000000003
			RIP: 0x00007FFF93BA0325
Jul 15 18:17:09 client: --- code ---
			0x7FFF93BA02E5: 2D263A02 004C89AC 24980000 0041BCC2
			0x7FFF93BA02F5: 0000004C 897C2450 4533ED41 BF030000
			0x7FFF93BA0305: 0066660F 1F840000 00000066 4439631C
			0x7FFF93BA0315: 0F858000 0000488B 0B48C7C0 FFFFFFFF
			0x7FFF93BA0325: 44386C01 01488D40 0175F548 8D1408C7
			0x7FFF93BA0335: 44242010 0000004C 8BCDE82C 14000084
			0x7FFF93BA0345: C0745348 8B430849 C7C0FFFF FFFF488B
			0x7FFF93BA0355: 13488906 4C896C24 4048C744 24480F00
Jul 15 18:17:09 client: --- stack ---
			0x003F67DFF910: 00000000 00000000 51BA6AB1 FF7F0000
			0x003F67DFF920: 17B1D2C3 10000000 E05A41A9 2C020000
			0x003F67DFF930: A05A41A9 2C020000 B147FDB2 FF7F0000
			0x003F67DFF940: 01000000 00000000 0741D293 FF7F0000
			0x003F67DFF950: 39FADF67 3F000000 00001000 00000000
			0x003F67DFF960: 00000000 00000000 C306CA0E AF460000
			0x003F67DFF970: E2090000 00000000 D540D293 FF7F0000
			0x003F67DFF980: 50F42723 2D020000 78F42723 2D020000
			0x003F67DFF990: 00F42723 2D020000 80254E9A 2B020000
			0x003F67DFF9A0: 00000000 00000000 FD31D093 FF7F0000
			0x003F67DFF9B0: 00000000 00000000 28F42723 2D020000
			0x003F67DFF9C0: 00000000 00000000 00000000 00000000
			0x003F67DFF9D0: EE0C0000 00000000 01000000 00000000
			0x003F67DFF9E0: 2C020000 00000000 00000000 00000000
			0x003F67DFF9F0: 8603FE7F 00000000 296102B3 FF7F0000
			0x003F67DFFA00: 50C88375 2C020000 18FCDF67 3F000000
			0x003F67DFFA10: 00C0BF67 3F000000 00000000 00000000
			0x003F67DFFA20: 2C020000 00000000 00000000 00000000
			0x003F67DFFA30: 00000000 00000000 00000000 00000000
			0x003F67DFFA40: 8603FE7F 00000000 191602B3 FF7F0000
			0x003F67DFFA50: 20D12C5E 2D020000 8603FE7F 00000000
			0x003F67DFFA60: E8D12C5E 2D020000 40EA7C33 2D020000
			0x003F67DFFA70: 00000000 00000000 00000000 00000000
			0x003F67DFFA80: 00000000 00000000 2059DB9F 2C020000
			0x003F67DFFA90: 500B65EF 2B020000 5A3100B3 FF7F0000
			0x003F67DFFAA0: 00000000 00000000 60EA7C33 2D020000
			0x003F67DFFAB0: 00000000 00000000 680B65EF 2B020000
			0x003F67DFFAC0: 500B65EF 2B020000 D1FADF67 3F000000
			0x003F67DFFAD0: 01000101 01000000 00000000 00000000
			0x003F67DFFAE0: 00000000 10000000 01000000 00000000
			0x003F67DFFAF0: 500B65EF 2B020000 00B0A167 3F000000
			0x003F67DFFB00: 500B65EF 2B020000 A055DB9F 2C020000
			0x003F67DFFB10: 0C000000 00000000 20EA7C33 2D020000
			0x003F67DFFB20: 02000000 00000000 00000000 00000000
Jul 15 18:17:09 client: --- trace ---
			ep 0x7FFF93BA0325 frame 0x003F67DFF9A0 rva 0x000000050325 in d3d9_arcdps_table @ get_release_addr
			ep 0x7FFF93D031FD frame 0x003F67DFF9F0 rva 0x0000000331FD in d3d9 @ e8
			ep 0x7FFFB3026129 frame 0x003F67DFFA40 rva 0x000000076129 in ntdll @ RtlGetSystemPreferredUILanguages
			ep 0x7FFFB3021619 frame 0x003F67DFFA90 rva 0x000000071619 in ntdll @ RtlSetCriticalSectionSpinCount
			ep 0x7FFFB300315A frame 0x003F67DFFD90 rva 0x00000005315A in ntdll @ TpReleaseCleanupGroupMembers
			ep 0x7FFFB16A7034 frame 0x003F67DFFDC0 rva 0x000000017034 in KERNEL32 @ BaseThreadInitThunk
			ep 0x7FFFB3002651 frame 0x003F67DFFE40 rva 0x000000052651 in ntdll @ RtlUserThreadStart
			thread start 0x7FFFB3002AD0 rva 0x000000052AD0 in ntdll @ TpReleaseCleanupGroupMembers

**Comment by knoxfighter** [comment]
Update to the newest version, this error was fixed in v2.2.1

**Comment by DoNotBlameItOnMe** [comment]
all is ok i've forget to enable notification upate, havent see there is a update, thanks.
