### ISSUE TITLE
Crashing again :(

### ISSUE THREAD

**Issue by DoNotBlameItOnMe** [knoxfighter/GW2-ArcDPS-Boon-Table#17]
In cold wars strike : 

Sep 04 15:14:12 arcdps 20210828.125821-373-x64
Sep 04 15:14:12 client: gw2 0x7FF6D2FF0000-0x7FF6D552D000 (0xDFD84B6D)
Sep 04 15:14:12 client: arcdps 0x7FF8A2C70000-0x7FF8A2D9B000 (0x19C222A4)
Sep 04 15:14:12 client: chainloading d3d9
Sep 04 15:14:13 extensions: Boon Table 0x7FF8A1B10000-0x7FF8A1CDD000 (2.3.0.0, 0x52D5E93C)
Sep 04 15:14:13 config: loading from "C:\Guild Wars 2\addons\arcdps\arcdps.ini"
Sep 04 15:14:13 client: ready
Sep 04 16:41:11 error: intercepted crash from hardware exception in "C:\Guild Wars 2\Gw2-64.exe"
Sep 04 16:41:11 client: --- exception ---
			code: 0x00000000C0000005
			addr: 0x00007FF6D3362D6D
			offs: 0x0000000000372D6D
			prms:   0000000000000002
			flgs: 0x0000000000000000
Sep 04 16:41:11 client: --- system ---
			windows: 10.0
			cpu: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
			ram: 11418MB / 16310MB used
			gpu: NVIDIA GeForce GTX 1660 SUPER
Sep 04 16:41:11 client: --- modules ---
			0x7FF6D2FF0000 - 0x7FF6D552D000    C:\Guild Wars 2\Gw2-64.exe
			0x7FF8F2410000 - 0x7FF8F2605000    C:\Windows\SYSTEM32\ntdll.dll
			0x7FF8F1350000 - 0x7FF8F140D000    C:\Windows\System32\KERNEL32.DLL
			0x7FF8EFD20000 - 0x7FF8EFFE9000    C:\Windows\System32\KERNELBASE.dll
			0x7FF8F2230000 - 0x7FF8F23D0000    C:\Windows\System32\USER32.dll
			0x7FF8F0390000 - 0x7FF8F03B2000    C:\Windows\System32\win32u.dll
			0x7FF8F0ED0000 - 0x7FF8F0EFA000    C:\Windows\System32\GDI32.dll
			0x7FF8F0080000 - 0x7FF8F018B000    C:\Windows\System32\gdi32full.dll
			0x7FF8F02F0000 - 0x7FF8F038D000    C:\Windows\System32\msvcp_win.dll
			0x7FF8EFC20000 - 0x7FF8EFD20000    C:\Windows\System32\ucrtbase.dll
			0x7FF8F1550000 - 0x7FF8F15FC000    C:\Windows\System32\ADVAPI32.dll
			0x7FF8F04E0000 - 0x7FF8F057E000    C:\Windows\System32\msvcrt.dll
			0x7FF8F0E30000 - 0x7FF8F0ECB000    C:\Windows\System32\sechost.dll
			0x7FF8F1220000 - 0x7FF8F134A000    C:\Windows\System32\RPCRT4.dll
			0x7FF8F0F10000 - 0x7FF8F0F7B000    C:\Windows\System32\WS2_32.dll
			0x7FF8EFFF0000 - 0x7FF8F0050000    C:\Windows\System32\WINTRUST.dll
			0x7FF8F04D0000 - 0x7FF8F04D8000    C:\Windows\System32\PSAPI.DLL
			0x7FF8F2100000 - 0x7FF8F222A000    C:\Windows\System32\ole32.dll
			0x7FF8E99F0000 - 0x7FF8E99FA000    C:\Windows\SYSTEM32\VERSION.dll
			0x7FF8ED210000 - 0x7FF8ED224000    C:\Windows\SYSTEM32\WTSAPI32.dll
			0x7FF8E4730000 - 0x7FF8E4757000    C:\Windows\SYSTEM32\WINMM.dll
			0x7FF8F1600000 - 0x7FF8F1955000    C:\Windows\System32\combase.dll
			0x7FF8F06A0000 - 0x7FF8F076D000    C:\Windows\System32\OLEAUT32.dll
			0x7FF8F19C0000 - 0x7FF8F20FF000    C:\Windows\System32\SHELL32.dll
			0x7FF8C0370000 - 0x7FF8C038E000    C:\Windows\SYSTEM32\MSACM32.dll
			0x7FF8F0190000 - 0x7FF8F02EF000    C:\Windows\System32\CRYPT32.dll
			0x7FF8DB590000 - 0x7FF8DB739000    C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.1151_none_91a40286cc884949\gdiplus.dll
			0x7FF8D7DB0000 - 0x7FF8D7E60000    C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
			0x7FF8CA8A0000 - 0x7FF8CA8C6000    C:\Windows\SYSTEM32\winmmbase.dll
			0x7FF8B8140000 - 0x7FF8B8159000    C:\Windows\SYSTEM32\USP10.dll
			0x7FF8DB740000 - 0x7FF8DB747000    C:\Windows\SYSTEM32\MSIMG32.dll
			0x7FF8D8510000 - 0x7FF8D851C000    C:\Windows\SYSTEM32\Secur32.dll
			0x7FF8EF510000 - 0x7FF8EF51C000    C:\Windows\SYSTEM32\CRYPTBASE.DLL
			0x7FF8EFA00000 - 0x7FF8EFA31000    C:\Windows\SYSTEM32\SSPICLI.DLL
			0x7FF8F10E0000 - 0x7FF8F1110000    C:\Windows\System32\IMM32.DLL
			0x7FF8EF720000 - 0x7FF8EF732000    C:\Windows\SYSTEM32\MSASN1.dll
			0x7FF8EFB40000 - 0x7FF8EFBC3000    C:\Windows\System32\bcryptPrimitives.dll
			0x7FF8DAC00000 - 0x7FF8DADE4000    C:\Windows\SYSTEM32\dbghelp.dll
			0x7FF8EDC70000 - 0x7FF8EE400000    C:\Windows\SYSTEM32\windows.storage.dll
			0x7FF8EF5A0000 - 0x7FF8EF5CC000    C:\Windows\SYSTEM32\Wldp.dll
			0x7FF8F1030000 - 0x7FF8F10DE000    C:\Windows\System32\SHCORE.dll
			0x7FF8F0470000 - 0x7FF8F04C5000    C:\Windows\System32\shlwapi.dll
			0x7FF8EFA80000 - 0x7FF8EFA9F000    C:\Windows\SYSTEM32\profapi.dll
			0x7FF8EDA70000 - 0x7FF8EDA82000    C:\Windows\SYSTEM32\kernel.appcore.dll
			0x7FF8F0050000 - 0x7FF8F0077000    C:\Windows\System32\bcrypt.dll
			0x7FF8ED5B0000 - 0x7FF8ED64E000    C:\Windows\system32\uxtheme.dll
			0x7FF8E97A0000 - 0x7FF8E97D1000    C:\Windows\SYSTEM32\cryptnet.dll
			0x7FF8F0F80000 - 0x7FF8F0F9D000    C:\Windows\System32\imagehlp.dll
			0x7FF8EF4F0000 - 0x7FF8EF508000    C:\Windows\SYSTEM32\CRYPTSP.dll
			0x7FF8EEC10000 - 0x7FF8EEC44000    C:\Windows\system32\rsaenh.dll
			0x7FF8E77D0000 - 0x7FF8E780B000    C:\Windows\SYSTEM32\dxcore.dll
			0x7FF8EFBD0000 - 0x7FF8EFC1E000    C:\Windows\System32\cfgmgr32.dll
			0x7FF8EE410000 - 0x7FF8EE433000    C:\Windows\SYSTEM32\gpapi.dll
			0x7FF8F1170000 - 0x7FF8F1219000    C:\Windows\System32\clbcatq.dll
			0x7FF8EE960000 - 0x7FF8EE993000    C:\Windows\SYSTEM32\ntmarta.dll
			0x7FF8D56E0000 - 0x7FF8D56F7000    C:\Windows\system32\napinsp.dll
			0x7FF8D56C0000 - 0x7FF8D56DB000    C:\Windows\system32\pnrpnsp.dll
			0x7FF8EA910000 - 0x7FF8EA925000    C:\Windows\system32\wshbth.dll
			0x7FF8EC550000 - 0x7FF8EC56D000    C:\Windows\system32\NLAapi.dll
			0x7FF8EEFA0000 - 0x7FF8EEFDB000    C:\Windows\SYSTEM32\IPHLPAPI.DLL
			0x7FF8EF300000 - 0x7FF8EF36A000    C:\Windows\System32\mswsock.dll
			0x7FF8EEFF0000 - 0x7FF8EF0BC000    C:\Windows\SYSTEM32\DNSAPI.dll
			0x7FF8F0F00000 - 0x7FF8F0F08000    C:\Windows\System32\NSI.dll
			0x7FF8D5650000 - 0x7FF8D5662000    C:\Windows\System32\winrnr.dll
			0x7FF8DD7F0000 - 0x7FF8DD86F000    C:\Windows\System32\fwpuclnt.dll
			0x7FF8DD7D0000 - 0x7FF8DD7DA000    C:\Windows\System32\rasadhlp.dll
			0x7FF8F0580000 - 0x7FF8F0695000    C:\Windows\System32\msctf.dll
			0x7FF8E6DA0000 - 0x7FF8E6E99000    C:\Windows\SYSTEM32\textinputframework.dll
			0x7FF8ECCA0000 - 0x7FF8ECD92000    C:\Windows\System32\CoreMessaging.dll
			0x7FF8EC940000 - 0x7FF8ECC9E000    C:\Windows\System32\CoreUIComponents.dll
			0x7FF8EC200000 - 0x7FF8EC354000    C:\Windows\SYSTEM32\wintypes.dll
			0x7FF8E94A0000 - 0x7FF8E9654000    C:\Windows\SYSTEM32\WindowsCodecs.dll
			0x7FF8E3E70000 - 0x7FF8E3F1C000    C:\Windows\SYSTEM32\TextShaping.dll
			0x7FF8B27D0000 - 0x7FF8B28E4000    C:\Guild Wars 2\bin64\CoherentUI64.dll
			0x7FF8A2C70000 - 0x7FF8A2D9B000    C:\Guild Wars 2\bin64\d3d9.dll
			0x7FF8E2670000 - 0x7FF8E2778000    C:\Windows\SYSTEM32\WINHTTP.dll
			0x7FF8EA3A0000 - 0x7FF8EA3AB000    C:\Windows\SYSTEM32\WINNSI.DLL
			0x7FF8E9BA0000 - 0x7FF8E9BB7000    C:\Windows\SYSTEM32\dhcpcsvc6.DLL
			0x7FF8EA350000 - 0x7FF8EA36D000    C:\Windows\SYSTEM32\dhcpcsvc.DLL
			0x7FF8D9F10000 - 0x7FF8D9FA9000    C:\Windows\SYSTEM32\webio.dll
			0x7FF8EF940000 - 0x7FF8EF94A000    C:\Windows\SYSTEM32\DPAPI.dll
			0x7FF8B3B20000 - 0x7FF8B3BED000    C:\Guild Wars 2\bin64\d3d9_chainload.dll
			0x7FF8DAB10000 - 0x7FF8DAB2B000    C:\Windows\SYSTEM32\VCRUNTIME140.dll
			0x7FF8DAA80000 - 0x7FF8DAB0D000    C:\Windows\SYSTEM32\MSVCP140.dll
			0x7FF8DAA70000 - 0x7FF8DAA7C000    C:\Windows\SYSTEM32\VCRUNTIME140_1.dll
			0x7FF896DF0000 - 0x7FF8971E7000    C:\Guild Wars 2\dxgi.dll
			0x7FF8E3350000 - 0x7FF8E3823000    C:\Windows\SYSTEM32\WININET.dll
			0x7FF8E2B80000 - 0x7FF8E2BA0000    C:\Windows\SYSTEM32\d3d12.dll
			0x7FF8EB790000 - 0x7FF8EBBED000    C:\Windows\SYSTEM32\d3dcompiler_47.dll
			0x7FF8E5280000 - 0x7FF8E544E000    C:\Windows\system32\d3d9.dll
			0x7FF8ED780000 - 0x7FF8ED7AF000    C:\Windows\SYSTEM32\dwmapi.dll
			0x7FF8E70F0000 - 0x7FF8E71F2000    C:\Windows\System32\DriverStore\FileRepository\nvmd.inf_amd64_1408eaf9a25ed64f\nvldumdx.dll
			0x7FF8953D0000 - 0x7FF896DEC000    C:\Windows\System32\DriverStore\FileRepository\nvmd.inf_amd64_1408eaf9a25ed64f\nvd3dumx.dll
			0x7FF8E4BA0000 - 0x7FF8E5276000    C:\Windows\SYSTEM32\nvapi64.dll
			0x7FF8F09B0000 - 0x7FF8F0E22000    C:\Windows\System32\SETUPAPI.DLL
			0x7FF8EE8B0000 - 0x7FF8EE90A000    C:\Windows\SYSTEM32\WINSTA.dll
			0x7FF8E27E0000 - 0x7FF8E2A90000    C:\Windows\SYSTEM32\iertutil.dll
			0x7FF8CCB00000 - 0x7FF8CCB17000    C:\Windows\SYSTEM32\ondemandconnroutehelper.dll
			0x7FF8E2310000 - 0x7FF8E24FC000    C:\Windows\SYSTEM32\urlmon.dll
			0x7FF8E22E0000 - 0x7FF8E2308000    C:\Windows\SYSTEM32\srvcli.dll
			0x7FF8EEFE0000 - 0x7FF8EEFEC000    C:\Windows\SYSTEM32\netutils.dll
			0x7FF8EEB30000 - 0x7FF8EEBC1000    C:\Windows\system32\schannel.DLL
			0x7FF8CD360000 - 0x7FF8CD376000    C:\Windows\SYSTEM32\mskeyprotect.dll
			0x7FF8EF5D0000 - 0x7FF8EF60B000    C:\Windows\SYSTEM32\NTASN1.dll
			0x7FF8EF610000 - 0x7FF8EF637000    C:\Windows\SYSTEM32\ncrypt.dll
			0x7FF8CD450000 - 0x7FF8CD476000    C:\Windows\system32\ncryptsslp.dll
			0x7FF8EE440000 - 0x7FF8EE534000    C:\Windows\system32\dxgi.dll
			0x7FF8A2790000 - 0x7FF8A295F000    C:\Windows\SYSTEM32\D3D12Core.dll
			0x7FF8B43E0000 - 0x7FF8B6EA1000    C:\Windows\System32\DriverStore\FileRepository\nvmd.inf_amd64_1408eaf9a25ed64f\nvwgf2umx.dll
			0x7FF8D6240000 - 0x7FF8D626B000    C:\Windows\SYSTEM32\D3DSCache.dll
			0x7FF8EFA40000 - 0x7FF8EFA6E000    C:\Windows\SYSTEM32\USERENV.dll
			0x7FF8E97E0000 - 0x7FF8E99E1000    C:\Windows\SYSTEM32\twinapi.appcore.dll
			0x7FF8A1B10000 - 0x7FF8A1CDD000    C:\Guild Wars 2\bin64\d3d9_arcdps_table.dll
			0x7FF8F1410000 - 0x7FF8F1466000    C:\Windows\System32\WLDAP32.dll
			0x7FF8C5120000 - 0x7FF8C52A6000    C:\Windows\System32\Speech\Common\sapi.dll
			0x7FF8CE000000 - 0x7FF8CE00B000    C:\Windows\SYSTEM32\msdmo.dll
			0x7FF8E8150000 - 0x7FF8E81D5000    C:\Windows\System32\MMDevApi.dll
			0x7FF8EF900000 - 0x7FF8EF934000    C:\Windows\System32\DEVOBJ.dll
			0x7FF8EC360000 - 0x7FF8EC546000    C:\Windows\SYSTEM32\dcomp.dll
			0x7FF8C0390000 - 0x7FF8C03D6000    C:\Windows\SYSTEM32\wdmaud.drv
			0x7FF8EA340000 - 0x7FF8EA34A000    C:\Windows\SYSTEM32\AVRT.dll
			0x7FF8C4F50000 - 0x7FF8C4F59000    C:\Windows\SYSTEM32\ksuser.dll
			0x7FF8D19C0000 - 0x7FF8D1B41000    C:\Windows\SYSTEM32\AUDIOSES.DLL
			0x7FF8EF0C0000 - 0x7FF8EF10B000    C:\Windows\SYSTEM32\powrprof.dll
			0x7FF8EEF80000 - 0x7FF8EEF92000    C:\Windows\SYSTEM32\UMPDC.dll
			0x7FF8C4AF0000 - 0x7FF8C4AFD000    C:\Windows\SYSTEM32\msacm32.drv
			0x7FF8C0360000 - 0x7FF8C036B000    C:\Windows\SYSTEM32\midimap.dll
			0x7FF8ED690000 - 0x7FF8ED6A4000    C:\Windows\SYSTEM32\resourcepolicyclient.dll
			0x7FF8E9330000 - 0x7FF8E93DE000    C:\Windows\SYSTEM32\mscms.dll
			0x7FF8E9310000 - 0x7FF8E9321000    C:\Windows\SYSTEM32\ColorAdapterClient.dll
			0x7FF8C69C0000 - 0x7FF8C6A03000    C:\Windows\SYSTEM32\icm32.dll
			0x7FF8D8D30000 - 0x7FF8D8DAB000    C:\Users\Vox\AppData\Local\Temp\E6223622-1658-4A83-8AE4-AF9C5808A7CB\bink2w64.dll
			0x7FF8D8B00000 - 0x7FF8D8B9C000    C:\Windows\SYSTEM32\DSOUND.DLL
			0x7FF8D8930000 - 0x7FF8D8A69000    C:\Windows\SYSTEM32\dxilconv.dll
Sep 04 16:41:11 client: --- registers ---
			RAX: 0x0000000000000000   R8:  0x000001DE9CBAA0C0
			RBX: 0x000001DFD83A3000   R9:  0x00000000AB04F187
			RCX: 0x0000000000000000   R10: 0x0000000000000007
			RDX: 0x0000000000000000   R11: 0x000001E08191D068
			RBP: 0x000000DB8A4FA370   R12: 0x000001DEA19EBD22
			RSP: 0x000000DB8A4FA2F0   R13: 0x000001DEA19EA8B0
			RSI: 0x0000000000000000   R14: 0x0000000000000000
			RDI: 0x000001DFD8385BF0   R15: 0x000001DF9F3AF288
			RIP: 0x00007FF6D3362D6D
Sep 04 16:41:11 client: --- code ---
			0x7FF6D3362D2D: 45B0488D 45B04889 B424A800 00000F10
			0x7FF6D3362D3D: 004C8974 24780F11 45B0488B 7DB8488B
			0x7FF6D3362D4D: 5DB09049 8B4F0848 85C97409 418B0748
			0x7FF6D3362D5D: 8D14C1EB 0233D248 3BDA0F84 9E000000
			0x7FF6D3362D6D: 8B338BCE E83A4000 004C8BF0 4885C074
			0x7FF6D3362D7D: 68E86D4D D4FF33C0 C745B001 0000004C
			0x7FF6D3362D8D: 8D4D3048 8945C04C 8D45B048 8945B849
			0x7FF6D3362D9D: 8BD4C745 C8000100 00498BCD 89742420
Sep 04 16:41:11 client: --- stack ---
			0x00DB8A4FA2D0: 00000000 00000000 00000000 00000000
			0x00DB8A4FA2E0: F82F3AD8 DF010000 762D36D3 F67F0000
			0x00DB8A4FA2F0: 00000000 DF010000 87F104AB DB000000
			0x00DB8A4FA300: 01000000 00000000 503D1E50 E0010000
			0x00DB8A4FA310: 0D030000 0A800000 25000000 00000000
			0x00DB8A4FA320: 01000000 DF010000 503D1E50 E0010000
			0x00DB8A4FA330: EAAA0400 0D030000 00010000 00000000
			0x00DB8A4FA340: 403CB2CE DF010000 27000000 DB000000
			0x00DB8A4FA350: 01000000 27000000 415A32D3 F67F0000
			0x00DB8A4FA360: 20A44F8A DB000000 2806F29C DE010000
			0x00DB8A4FA370: 00000000 00000000 E4ED42D3 F67F0000
			0x00DB8A4FA380: 18A44F8A DB000000 415A32D3 F67F0000
			0x00DB8A4FA390: 1006F29C DE010000 F818DED4 F67F0000
			0x00DB8A4FA3A0: 0D030000 DE010000 F805F29C DE010000
			0x00DB8A4FA3B0: 90F535AB DE010000 00000000 00000000
			0x00DB8A4FA3C0: 00000000 00000000 00000000 00000000
			0x00DB8A4FA3D0: B0A89EA1 DE010000 2531DDD3 F67F0000
			0x00DB8A4FA3E0: 30A9049D DE010000 0094A8A1 DE010000
			0x00DB8A4FA3F0: 00000000 00000000 00000000 00000000
			0x00DB8A4FA400: 0094A8A1 DE010000 1BA41AD4 F67F0000
			0x00DB8A4FA410: B0A89EA1 DE010000 B0A89EA1 DE010000
			0x00DB8A4FA420: 22BD9EA1 DE010000 B0A89EA1 DE010000
			0x00DB8A4FA430: 01200000 DE010000 A0A64F8A DB000000
			0x00DB8A4FA440: 10A54F8A DB000000 38A9049D DE010000
			0x00DB8A4FA450: 0094A8A1 DE010000 7B831AD4 F67F0000
			0x00DB8A4FA460: 90F535AB DE010000 05000000 00000000
			0x00DB8A4FA470: 03000000 00000000 01000000 00000000
			0x00DB8A4FA480: 43144901 00000000 34AD1AD4 F67F0000
			0x00DB8A4FA490: 00000000 00000000 0094A8A1 DE010000
			0x00DB8A4FA4A0: A0A64F8A DB000000 10A54F8A DB000000
			0x00DB8A4FA4B0: 07040000 00000000 51BA36F1 F87F0000
			0x00DB8A4FA4C0: CEA1A736 32000000 233220F2 C906D2E8
			0x00DB8A4FA4D0: C2ACF193 EA8C6363 57214218 682C667C
			0x00DB8A4FA4E0: 38A9049D DE010000 D9EFC9D3 F67F0000
Sep 04 16:41:11 client: --- trace ---
			ep 0x7FF6D3362D6D frame 0x00DB8A4FA380 rva 0x000000372D6D in Gw2-64
			ep 0x7FF6D3325A41 frame 0x00DB8A4FA3D0 rva 0x000000335A41 in Gw2-64
			ep 0x7FF6D3DD3125 frame 0x00DB8A4FA400 rva 0x000000DE3125 in Gw2-64
			ep 0x7FF6D41AA41B frame 0x00DB8A4FA480 rva 0x0000011BA41B in Gw2-64
			ep 0x7FF6D41AAD34 frame 0x00DB8A4FA4E0 rva 0x0000011BAD34 in Gw2-64
			ep 0x7FF6D3C9EFD9 frame 0x00DB8A4FA530 rva 0x000000CAEFD9 in Gw2-64
			ep 0x7FF6D41B175E frame 0x00DB8A4FA590 rva 0x0000011C175E in Gw2-64
			ep 0x7FF6D41B4365 frame 0x00DB8A4FF300 rva 0x0000011C4365 in Gw2-64
			ep 0x7FF6D41B393D frame 0x00DB8A4FF3C0 rva 0x0000011C393D in Gw2-64
			ep 0x7FF6D41B161D frame 0x00DB8A4FF3F0 rva 0x0000011C161D in Gw2-64
			ep 0x7FF6D419DE8B frame 0x00DB8A4FF480 rva 0x0000011ADE8B in Gw2-64
			ep 0x7FF6D30C3BE3 frame 0x00DB8A4FF4D0 rva 0x0000000D3BE3 in Gw2-64
			ep 0x7FF6D30C3B58 frame 0x00DB8A4FF500 rva 0x0000000D3B58 in Gw2-64
			ep 0x7FF6D30C148E frame 0x00DB8A4FF540 rva 0x0000000D148E in Gw2-64
			ep 0x7FF6D30BBFC7 frame 0x00DB8A4FF6D0 rva 0x0000000CBFC7 in Gw2-64
			ep 0x7FF6D30BD0AD frame 0x00DB8A4FF700 rva 0x0000000CD0AD in Gw2-64
			ep 0x7FF6D30BC491 frame 0x00DB8A4FF730 rva 0x0000000CC491 in Gw2-64
			ep 0x7FF6D3253A71 frame 0x00DB8A4FF760 rva 0x000000263A71 in Gw2-64
			ep 0x7FF8F1367034 frame 0x00DB8A4FF790 rva 0x000000017034 in KERNEL32 @ BaseThreadInitThunk
			ep 0x7FF8F2462651 frame 0x00DB8A4FF810 rva 0x000000052651 in ntdll @ RtlUserThreadStart
			thread start 0x7FF6D3253A14 rva 0x000000263A14 in Gw2-64

**Comment by knoxfighter** [comment]
It seems that is an internal gw2 crash, i don't see my plugin there at all :(
Does that happen all the time or only sometimes?

**Comment by DoNotBlameItOnMe** [comment]
Idk i have unistall boon table because i dont want more crash , i was thinking it's caused by your last update, but semms it's not u.
