### ISSUE TITLE
Windows defender is falsely detecting it as Trojan

### ISSUE THREAD

**Issue by Candra-Moon** [knoxfighter/GW2-ArcDPS-Boon-Table#19]
I had to be quick at getting the scan to figure out why Windows was immediately deleting this on download and I got this: [https://imgur.com/Vcjdb3C](https://imgur.com/Vcjdb3C)

**Comment by knoxfighter** [comment]
That is wrongly detected by the windows defender. I am currently trying to resolve that mistake.

**Comment by knoxfighter** [comment]
> We have removed the detection.  Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 
>      1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
>      2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
>      3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus
> 
> Thank you for contacting Microsoft.

So it should stop getting detected as Trojan 😄
