### ISSUE TITLE
Einstellungen werde nicht gespeichert

### ISSUE THREAD

**Issue by master1782** [knoxfighter/GW2-ArcDPS-Boon-Table#26]
Seit der Version 2.4.4 weden mein Einstellungen die ich gamacht habe nicht gespeichert und ich muss jedesmal alles neu einstellen was ziemlich nervig ist da es mit der Vorgängerversion super funktioniert hat.
Was wurde bei der Version 2.4.4 zu der Version 2.4.3 geändert das es nicht mehr so funktioniert wie ich es gewohnt war.

**Comment by DoubleHighC** [comment]
Hey! Da gibt es schon einen Eintrag auf English! "settings reset" gleich 4 Punkte unter deinem!

Anscheinend gibt es keine Antwort bisher, da der Programmierer das Problem nicht reproduzieren kann!
Ich habe das Problem auch und einige Anderen auch, aber das wird wohl noch ne ganze Weile dauern bis
da ne Problemlösung gefunden wird!

LG

**Comment by knoxfighter** [comment]
Jap, der Fehler passiert mittlerweile jedes mal. Ich kann den leider nicht ohne weiteres fixes, ohne große umbauten zu machen. Da ich aktuell eh komplett alles neu schreibe, wird dieser Fehler noch ein wenig bestehen. Tut mir Leid für die Unannehmlichkeiten.
