### ISSUE TITLE
Show header with text instead of images

### ISSUE THREAD

**Issue by Giganticjuan** [knoxfighter/GW2-ArcDPS-Boon-Table#29]
the show header with text instead of images is on and cannot be turned off. 
![image](https://user-images.githubusercontent.com/122524701/212035183-168ba794-8550-4ed0-8cea-097e1f7a6ced.png)
I tried making some changes to arcdps_table.ini, specifically show_label = false to show_label = true, run the game open to see a change which there wasn't any. Then change the setting back and test it again but no change. 
![image](https://user-images.githubusercontent.com/122524701/212035696-606c4dd5-d5c4-4c87-9c9a-4a5af3d02f6c.png)
Any idea why I cant uncheck the box?

**Comment by knoxfighter** [comment]
I removed support to show icons when using dx9. Please switch to dx11 and you will be able to change that setting.
