### ISSUE TITLE
Option to only show your subgroup

### ISSUE THREAD

**Issue by xps1992** [knoxfighter/GW2-ArcDPS-Boon-Table#3]
Hi,
thanks for the gui update.

I played around with it a bit today and found that the "Subgroups" option has no function. 

It would also be great that you can only show one group and the players that belong to it.

**Comment by knoxfighter** [comment]
Subgroups will only be shown in squads with more than 5 people in it. And when that is the case, it is working fine for me.

**Comment by hk3wx** [comment]
isn't this option supposed to show only your subgroup not all?

**Comment by knoxfighter** [comment]
No, the option will show subgroups in general, the plugin has 3 groups (players, subgroups, total). And you can stop displaying that. It is not yet possible to only show your subgroup.

**Comment by knoxfighter** [comment]
Implemented with new release v2.1.0

**Comment by hk3wx** [comment]
> Implemented with new release v2.1.0

Thank you so much!
<3
