### ISSUE TITLE
New font display suggestions

### ISSUE THREAD

**Issue by jiangyi0923** [knoxfighter/GW2-ArcDPS-Boon-Table#8]
I noticed that you did not add a font callback, this will cause some computers to display other language characters, like Chinese characters, which will be "?"
You can do this:

ImGui::PushFont(ImGui::GetIO().Fonts->Fonts.back());
ImGui::Begin()

ImGui::End(); 
ImGui::PopFont();

This makes it safer to call fonts

**Comment by knoxfighter** [comment]
I added it, it seems that some kind of helps. I don't understand why that is needed, but it helps xD
